export const collections = [
  {
    id: 1,
    title: "React Resources",
    description: "Essential React tutorials and documentation for frontend development",
    tags: ["react", "frontend", "coding"],
    links: 23,
  },
  {
    id: 2,
    title: "Next.js Mastery",
    description: "App Router, Server Components, and full-stack Next.js guides",
    tags: ["nextjs", "react", "fullstack"],
    links: 18,
  },
  {
    id: 3,
    title: "JavaScript Core",
    description: "Deep dive into JavaScript fundamentals and advanced concepts",
    tags: ["javascript", "programming", "basics"],
    links: 30,
  },
  {
    id: 4,
    title: "TypeScript Power",
    description: "Type-safe patterns, tips, and real-world TypeScript usage",
    tags: ["typescript", "javascript", "typing"],
    links: 16,
  },
  {
    id: 5,
    title: "Backend with Node.js",
    description: "APIs, authentication, and backend architecture using Node.js",
    tags: ["nodejs", "backend", "api"],
    links: 21,
  },
  {
    id: 6,
    title: "Database & SQL",
    description: "SQL queries, schema design, and database optimization",
    tags: ["database", "sql", "backend"],
    links: 14,
  },
  {
    id: 7,
    title: "Prisma & ORM",
    description: "Modern database access using Prisma and best ORM practices",
    tags: ["prisma", "orm", "database"],
    links: 12,
  },
  {
    id: 8,
    title: "Supabase Stack",
    description: "Auth, storage, realtime, and backend-as-a-service with Supabase",
    tags: ["supabase", "backend", "baas"],
    links: 19,
  },
  {
    id: 9,
    title: "UI & UX Design",
    description: "Design systems, UX principles, and clean UI inspiration",
    tags: ["ui", "ux", "design"],
    links: 25,
  },
  {
    id: 10,
    title: "Tailwind CSS",
    description: "Utility-first styling patterns and responsive layouts",
    tags: ["tailwind", "css", "frontend"],
    links: 17,
  },
  {
    id: 11,
    title: "Mobile Development",
    description: "React Native, Flutter, and mobile-first development resources",
    tags: ["mobile", "react-native", "flutter"],
    links: 20,
  },
  {
    id: 12,
    title: "System Design",
    description: "Scalable architecture, APIs, and backend system design concepts",
    tags: ["system-design", "architecture", "backend"],
    links: 11,
  },
  {
    id: 13,
    title: "Dev Tools & Productivity",
    description: "VS Code tips, extensions, CLI tools, and workflows",
    tags: ["tools", "productivity", "dev"],
    links: 22,
  },
  {
    id: 14,
    title: "Career & Interviews",
    description: "Interview prep, CV tips, and real-world dev career advice",
    tags: ["career", "interview", "jobs"],
    links: 15,
  },
];
